# Generated by Django 3.0.5 on 2020-05-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200520_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='chead2',
            field=models.TextField(),
        ),
    ]
