# Generated by Django 3.0.5 on 2020-05-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200520_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=30)),
                ('desc', models.TextField()),
            ],
        ),
    ]
