# Generated by Django 3.0.5 on 2020-05-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
